name: Build Azure Function artifact 

on:
  workflow_call:
    inputs:
      python_version:
        description: The python version to use
        required: true
        type: string


jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: pip install --target="./.python_packages/lib/site-packages" -e . 

      - name: Zip artifact for deployment
        run: zip release.zip ./* ./.python_packages !README.md !terraform -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: mde-fixit-integration
          path: |
            release.zip
            !.venv/