name: Deploy Azure Function to Azure Portal

on:
  workflow_call:
    inputs:
      deploy_env:
        description: Deployment environment
        required: true
        type: string

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./"
    
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    if: inputs.deploy_env == 'prod' || inputs.deploy_env == 'stag'

    environment: ${{ inputs.deploy_env }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: mde-fixit-integration 
        
      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Get deployment slot
        id: get-deployment-slot
        run: |
          if [[ ${{ inputs.deploy_env }} == 'prod' ]]; then
            echo "DEPLOY_SLOT=production" >> $GITHUB_OUTPUT
          elif [[ ${{ inputs.deploy_env }} == 'stag' ]]; then
            echo "DEPLOY_SLOT=staging" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'mde-fixit-integration-fa'
          slot-name: ${{steps.get-deployment-slot.outputs.DEPLOY_SLOT }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          