name: Deploy Azure Function to Azure Portal

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: Deployment environment
        required: true
        type: string

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
    
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    if: inputs.DEPLOY_ENV == 'prod' || inputs.DEPLOY_ENV == 'stag'

    environment: ${{ inputs.DEPLOY_ENV }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mde-fixit-integration 
        
      - name: Unzip artifact for deployment
        run: unzip release.zip     

      - name: Display structure of downloaded files
        run: ls -Ra
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'fa-mde-fixit-integration'
          slot-name: ${{ inputs.DEPLOY_ENV }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          