name: Project pipepline

on:
  push:
    branches:
      - "**"

    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:
  prepare-pipeline:
    uses: "./.github/workflows/prepare-pipeline.yml"
    secrets: inherit
  
  lint-and-test:
    needs: [prepare-pipeline]
    uses: "./.github/workflows/lint-and-test.yml"
    secrets: inherit

  build-and-upload:
    uses: "./.github/workflows/build-and-upload.yml"
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      PYTHON_VERSION: ${{ needs.prepare-pipeline.outputs.python_version }}

  deploy:
    uses: "./.github/workflows/deploy-fa.yml"
    needs: [prepare-pipeline, build-and-upload]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
    
