name: Project pipepline

on:
  push:
    branches:
      - "**"

    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'

  workflow_dispatch:


jobs:
  prepare:
    uses: "./.github/workflows/prepare.yml"
    secrets: inherit

  build:
    uses: "./.github/workflows/build.yml"
    needs: [prepare]
    secrets: inherit
    with:
      PYTHON_VERSION: "3.11"

  deploy:
    uses: "./.github/workflows/deploy.yml"
    needs: [prepare, build]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare.outputs.DEPLOY_ENV }}
    
