name: Project pipepline

on:
  push:
    branches:
      - "**"

    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:
  prepare:
    uses: "./.github/workflows/prepare-pipeline.yml"
    secrets: inherit

  build:
    uses: "./.github/workflows/build-and-upload.yml"
    needs: [prepare]
    secrets: inherit
    with:
      PYTHON_VERSION: ${{ needs.prepare.outputs.python_version }}

  deploy:
    uses: "./.github/workflows/deploy-fa.yml"
    needs: [prepare, build]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare.outputs.deploy_env }}
    
