name: Prepare pipeline 

on:
  workflow_call:
    outputs:
      DEPLOY_ENV:
        description: Deployment environment 
        value: ${{ jobs.prepare-pipeline.outputs.DEPLOY_ENV }}
      
jobs:
  prepare-pipeline:
      runs-on: ubuntu-latest

      outputs:
        DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set deployment variable 
          id: deploy-env
          env:
            BRANCH: ${{ github.ref_name }}
          run: |
            if [[ $BRANCH == "main" || $BRANCH == "master" ]]; then
                DEPLOY_ENV="prod"
            elif [[ $BRANCH == "staging" ]]; then
                DEPLOY_ENV="stag"
            else
                DEPLOY_ENV="dev"
            fi
            echo "DEPLOY_ENV=$DEPLOY_ENV"
            echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_OUTPUT

        - name: Write prepare summary
          env:
            DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
          run: |
            echo "### Prepare pipeline:               
            <table>
              <tr>
                <td>🎯 Deploy env</td>
                <td>$DEPLOY_ENV</td>
              </tr>
            </table>" >> $GITHUB_STEP_SUMMARY