name: Prepare pipeline 

on:
  workflow_call:
    outputs:
      deploy_env:
        description: Deployment environment 
        value: ${{ jobs.prepare-pipeline.outputs.DEPLOY_ENV }}
      
      python_version:
        description: Python version
        value: ${{ jobs.prepare-pipeline.outputs.PYTHON_VERSION }}
      
jobs:
  prepare-pipeline:
      runs-on: ubuntu-latest

      outputs:
        DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
        PYTHON_VERSION: ${{ steps.python-version.outputs.PYTHON_VERSION }}

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set Python version
          id: python-version
          run: |
            if [[ -f ".python-version" ]]; then
                PYTHON_VERSION=$(cat .python-version)
            else
              echo "Missing \".python-version\" file"
              exit 1
            fi
            echo "PYTHON_VERSION=$PYTHON_VERSION"
            echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_OUTPUT

        - name: Set deployment variable 
          id: deploy-env 
          env:
            BRANCH: ${{ github.ref_name }}
          run: |
            if [[ $BRANCH == "main" || $BRANCH == "master" ]]; then
                DEPLOY_ENV="prod"
            elif [[ $BRANCH == "staging" ]]; then
                DEPLOY_ENV="stag"
            else
                DEPLOY_ENV="dev"
            fi
            echo "DEPLOY_ENV=$DEPLOY_ENV"
            echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_OUTPUT
          
        - name: Write prepare summary
          env:
            PYTHON_VERSION: ${{ steps.python-version.outputs.PYTHON_VERSION }}
            DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
          run: |
            echo "### Prepare pipeline:               
            <table>
              <tr>
                <td>🐍 Python version</td>
                <td>$PYTHON_VERSION</td>
              </tr>
              <tr>
                <td>🎯 Deploy env</td>
                <td>$DEPLOY_ENV</td>
              </tr>
            </table>" >> $GITHUB_STEP_SUMMARY